name: Deploy VORTEX AI Engine to WordPress

on:
  push:
    branches: [ development, main ]
  release:
    types: [ published ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
        extensions: mysqli, curl, openssl, mbstring, xml, json
        coverage: none
        
    - name: Install Composer dependencies
      run: |
        composer install --no-dev --optimize-autoloader
        
    - name: Create plugin ZIP
      run: |
        # Create a clean plugin directory
        mkdir -p vortex-ai-engine-deploy
        cp -r vortex-ai-engine/* vortex-ai-engine-deploy/
        cp -r admin vortex-ai-engine-deploy/
        cp -r includes vortex-ai-engine-deploy/
        cp -r vault-secrets vortex-ai-engine-deploy/
        cp -r assets vortex-ai-engine-deploy/
        cp -r templates vortex-ai-engine-deploy/
        cp -r languages vortex-ai-engine-deploy/
        cp composer.json vortex-ai-engine-deploy/
        cp readme.txt vortex-ai-engine-deploy/
        
        # Remove unnecessary files
        rm -rf vortex-ai-engine-deploy/vendor
        rm -rf vortex-ai-engine-deploy/tests
        rm -rf vortex-ai-engine-deploy/backup-local-files
        rm -rf vortex-ai-engine-deploy/infra
        rm -rf vortex-ai-engine-deploy/solana-program
        rm -rf vortex-ai-engine-deploy/contracts
        rm -rf vortex-ai-engine-deploy/blockchain
        
        # Create ZIP file
        zip -r vortex-ai-engine.zip vortex-ai-engine-deploy/
        
    - name: Upload plugin ZIP as artifact
      uses: actions/upload-artifact@v3
      with:
        name: vortex-ai-engine-plugin
        path: vortex-ai-engine.zip
        
    - name: Deploy to WordPress (SFTP)
      if: github.ref == 'refs/heads/main' || github.event_name == 'release'
      uses: wlixcc/SFTP-Deploy-Action@v1.2.4
      with:
        username: ${{ secrets.WP_SFTP_USERNAME }}
        server: ${{ secrets.WP_SFTP_SERVER }}
        ssh_private_key: ${{ secrets.WP_SFTP_PRIVATE_KEY }}
        local_path: './vortex-ai-engine-deploy/*'
        remote_path: './public_html/wp-content/plugins/vortex-ai-engine/'
        delete_remote_files: true
        
    - name: Deploy to WordPress (SSH)
      if: github.ref == 'refs/heads/main' || github.event_name == 'release'
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.WP_SSH_HOST }}
        username: ${{ secrets.WP_SSH_USERNAME }}
        key: ${{ secrets.WP_SSH_PRIVATE_KEY }}
        script: |
          cd /var/www/html/wp-content/plugins/
          rm -rf vortex-ai-engine
          mkdir vortex-ai-engine
          cd vortex-ai-engine
          # Extract and set permissions
          chmod -R 755 .
          find . -type f -exec chmod 644 {} \;
          
    - name: Create Release
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ github.run_number }}
        release_name: VORTEX AI Engine v${{ github.run_number }}
        body: |
          ## VORTEX AI Engine Plugin Update
          
          ### Changes in this release:
          - Automated deployment from GitHub
          - Updated plugin files
          - Improved WordPress compatibility
          
          ### Installation:
          1. Download the ZIP file from this release
          2. Upload to WordPress via Plugins > Add New > Upload Plugin
          3. Activate the plugin
          
          ### Files included:
          - Main plugin file: `vortex-ai-engine.php`
          - Admin interface
          - Core includes and algorithms
          - Assets (CSS/JS)
          - Templates
        draft: false
        prerelease: false
        
    - name: Upload Release Asset
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./vortex-ai-engine.zip
        asset_name: vortex-ai-engine.zip
        asset_content_type: application/zip 